### ISSUE TITLE
Feature request: Manually control the compilation import-path

### ISSUE THREAD

**Issue by joh-ivu** [ascopes/protobuf-maven-plugin#135]
In a company-internal project I have the following setup:

* The FooBar project shall publish some .proto files
* Those protos depend on other protos coming from Maven dependencies. There are three dependencies in total:
  * com.google.api.grpc:proto-google-common-protos (a jar with both .class and .proto files)
  * my.company:stuff (a zip with .proto files)
  * my.company:things (a zip with .proto files)
* There are transitive dependencies between them: stuff depends both on things and proto-google-common-protos

I want to do two things in the FooBar project:
1. I want to invoke protoc with the FooBar .proto files as an automated sanity check. That already works with the plugin.
2. I want to compile the generated .java files in order to run an additional integration test with the generated classes.

For 2. to work, I need to compile the .java files resulting from the FooBar .proto files. Those classes however import classes that would result from stuff.proto and things.proto because of the dependencies within the .proto files. Since the stuff and things dependencies only provide the .protos, not precompiled .class files like the google dependency does, I would have to compile things.proto and stuff.proto as well. I tried to configure an additional execution of the plugin to do that.

However, the plugin always adds _all_ dependencies to as includes so that things.proto appears both as a source-to-compile and as an import for the compilation which protoc quite sensibly does not accept. I know that I can already _add_ more imports, but as far I as can see there is no way to exclude imports.

I propose a toggleable mode which lets me explicitly control the import path for compilation. I understand that my case is more complicated than one would like to deal with once transitive dependencies enter the picture, so I would still be happy if that mode did not automatically resolve transitive dependency like the normal operation of the plugin does.

**Comment by ascopes** [comment]
So effectively a way of preventing automatic dependency resolution? If so, I can definitely add that.

**Comment by ascopes** [comment]
Just for my understanding, so you have `FooBar` and that gets compiled, but you are trying to also compile additional resources outside the current project as well which is the issue you are seeing?

Might not have time to look into this immediately as I have some stuff coming up for a couple of weeks where I won't have access to a computer but I can try and think up some ideas around this if that sounds okay?

**Comment by joh-ivu** [comment]
I can already compile additional .proto files by having a second execution with a specific source directory (which I can fill with .proto files by using the maven-dependency-plugin before). The problem is that the protoc-invocation will fail when the same .proto file is both a source-to-compile and an imported file.

Please, don't feel rushed. You get to it when you get to it. And if you don't, then my team will have to work out a different solution themselves.

**Comment by ascopes** [comment]
Are you able to provide a dummy example of how you'd structure this project? Just gives me something to make an integration test for so I make sure I don't miss anything important!

**Comment by ascopes** [comment]
Ok so summarising, it sounds like the functionality for this suite of use cases needs:

1. The ability to control whether Maven dependencies are pulled in recursively, only directly, or not at all (thinking of adding an enum for this purpose). This would let you take complete control on the import path itself.
2. The ability to add Maven artifacts as dependencies that have to be compiled with the build (i.e. including a zip archive from a Maven repository that is also compiled to Java sources with your project). This would then be usable with the first part to allow you to compile the `mycompany.stuff` ZIP without needing to unpack it elsewhere first, and have explicit control over what you are including.

I think this would solve your use case, does this sound like what you are looking for, or is there anything else I am missing here?

**Comment by ascopes** [comment]
Update on the progress for this.

- GH-139 implements a mechanism to control whether dependencies are globally resolved recursively or only directly.
- GH-153 implements the ability to add custom archive artifacts located on Maven repositories as compilable sources to the project. This also adds the ability to control recursive resolution of individual dependencies.

**Comment by ascopes** [comment]
Update on the progress for this.

- GH-139 implements a mechanism to control whether dependencies are globally resolved recursively or only directly, providing the ability to include or exclude those dependencies as you need.
- GH-153 implements the ability to add custom archive artifacts located on Maven repositories as compilable sources to the project. This also adds the ability to control recursive resolution of individual dependencies, which I believe is what you're trying to work around with the example you gave in the description.
- GH-154 adds the ability to ignore project dependencies in the import path entirely.
- GH-155 adds the ability to add explicit import paths using Maven dependencies, providing some additional fine grained control over importing dependencies and controlling whether they are handled recursively or not.

All of these are currently on `main`. If you have time, please can you take a look at them and see if they cover what you are looking for? If this is what you need then I will proceed to set up the full test packs for those features (holding off doing that until I have confirmation that this does what you need).

Thanks for the patience. I'll look into releasing this as a new version once it is confirmed.

**Comment by ascopes** [comment]
I've released this under 1.2.0-rc1 provisionally.

**Comment by ascopes** [comment]
Going to assume that this is okay to close as completed. If there are any issues with 1.2.0, please can you raise a new issue and let me know.

**Comment by joh-ivu** [comment]
But on the bright side: A slightly different configuration works for my use-case :-)

**Comment by ascopes** [comment]
This causes #164 (fixed in #171), and a reproduction for the original issue as part of #172 which now tracks that defect.
