### ISSUE TITLE
Have custom out specifications to match custom plugins

### ISSUE THREAD

**Issue by anthonyalayo** [ascopes/protobuf-maven-plugin#166]
Hey there,

When using custom binaries, usually those binaries need to have their own custom `out` param.

For example, `--custom-bin_out=...`

However over here, it looks like it's always set to the language:
https://github.com/ascopes/protobuf-maven-plugin/blob/404729d4d1a2eb11bc1417fea31e4e55e343537d/src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java#L64-L72

Here's an example of having a custom out:
https://github.com/anthonyalayo/protoc-gen-pubsub-schema

**Comment by anthonyalayo** [comment]
In the original fork of this project, I can see that it is using the plugin id instead:
https://github.com/xolstice/protobuf-maven-plugin/blob/fe8e6448dc6a5d58019b47a6fa7d348f8acd28e5/src/main/java/org/xolstice/maven/plugin/protobuf/Protoc.java#L269

**Comment by anthonyalayo** [comment]
Correct the above, i do see something like that here too, so trying to spot the discrepancy:

https://github.com/ascopes/protobuf-maven-plugin/blob/7dfc72ac347a687f8e4861789b4d1be07dfcf385/src/main/java/io/github/ascopes/protobufmavenplugin/execute/ArgLineBuilder.java#L81-L90

**Comment by anthonyalayo** [comment]
Okay I think I figured out all the nuances, I'll close this issue as well as it doesn't accurately reflect the problem.

**Comment by ascopes** [comment]
@anthonyalayo Just seen this properly... glad you've worked it out.

It is worth being aware this isn't forked from Xolstice's Maven plugin but is built totally from scratch, so some functionality will not match that plugin.

If you do find any confusing or missing functionality, please raise an issue for it. 

If it is missing we can definitely consider adding it...

...and if it is confusing, then I've either designed it poorly or documented it poorly so you won't be the only one having issues most likely!

**Comment by anthonyalayo** [comment]
With v2.0.0, it's the best plugin there is. Hopefully SEO kicks in soon enough. 😀
