### ISSUE TITLE
Add a `skip` parameter

### ISSUE THREAD

**Issue by ascopes** [ascopes/protobuf-maven-plugin#184]
To compliment other Maven plugins

- [x] Add a parameter of type `boolean` named `skip` to `AbstractGenerateMojo`
    - ...use the `@Parameter` annotation to specify a default property to override it (`protobuf.skip`).
    - ...use the `@Parameter` annotation to default it to `"false"`.

- [x] Add a unit test for this in the AbstractGenerateMojoTestTemplate class.
- [x] Add an integration test case in `src/it` that covers this attribute being set to `true` in the plugin configuration.
    - Ensure it compiles some protobuf sources before the flag is set to skip the execution.
    - Test that the plugin does not run when it is set. You can check for this using the presence of target/protobuf-maven-plugin as an indicator that it did run.

**Comment by rohit-satya** [comment]
@ascopes Please assign this to me

**Comment by ascopes** [comment]
Will do

**Comment by ascopes** [comment]
@rohit-satya if you need any assistance or help or further details, please let me know. Hoping to get this in as a v2.0.0 feature!

**Comment by ascopes** [comment]
Since we want this in 2.0.0, and I haven't heard anything back in the past week, going to pick this up this morning so I can get 2.0.0 out this afternoon.

**Comment by ascopes** [comment]
Released under v2.0.0 as stable.
