### ISSUE TITLE
Documentation suggests using `pyiEnabled` flag but the code needs `pythonStubsEnabled`

### ISSUE THREAD

**Issue by ielis** [ascopes/protobuf-maven-plugin#199]
Dear @ascopes 
thank you very much for an awesome plugin! I would like to point out one issue in the documentation, I believe there is a bug there.

The documentation for building Python typeshed stubs [suggests](https://github.com/ascopes/protobuf-maven-plugin/blob/215fe183fedb7caeee47499c11092a450f222e73/protobuf-maven-plugin/src/site/markdown/index.md?plain=1#L285) using `pyiEnabled` flag.
However, the actual code [needs](https://github.com/ascopes/protobuf-maven-plugin/blob/8a9bf5b116ff587359abcd6902ff735d19c65ad2/protobuf-maven-plugin/src/main/java/io/github/ascopes/protobufmavenplugin/AbstractGenerateMojo.java#L534) requires `pythonStubsEnabled` flag. Therefore, the [documentation](https://ascopes.github.io/protobuf-maven-plugin/#generating-other-language-sources) probably needs to be updated.

The plugin ran as expected for me when using `pythonStubsEnabled`.

Thanks a lot for the plugin!

**Comment by ascopes** [comment]
Hey, thanks for raising this, would you be interested in submitting a patch for this?

If not, I am happy to pick this up!

**Comment by ascopes** [comment]
Thanks for fixing this. I've just deployed the [fixed GitHub pages](https://ascopes.github.io/protobuf-maven-plugin).
