### ISSUE TITLE
Support code generator plugins with injection point

### ISSUE THREAD

**Issue by virgilsky** [ascopes/protobuf-maven-plugin#269]
Protobuf custom code generator plugins can [inject](https://protobuf.dev/reference/java/java-generated/#plugins) code at the given insertion point. The insertion point must refer to a file generated upstream by either the specific language generator, or another plugin.
In my particular scenario, I am trying to generate code with my custom plugin and insert it in the Java specific code generated by protoc. However, the order in which the arguments to protoc are specified, is crucial, i.e. the `--java_out` argument should precede my custom plugin's out.
For that reason, I propose to modify the usage of `ArgLineBuilder` in `SourceCodeGenerator`, to first specify the enabled languages and then the resolved plugins.

**Comment by ascopes** [comment]
I was just having a think about this. Are there any cases do we think where the converse to this would be true (i.e. the user would want the plugin to execute after the code generation)?

I am wondering if it is worth having functionality to allow specifying whether the plugin runs first or last. I am not sure if this would be needed though as I have not ever really had to work with such constraints myself.

**Comment by virgilsky** [comment]
I don't think this would be the case. That would mean the language specific generators would try to insert code into the code generated by a particular plugin.
What you might consider, is to allow full control of the order in which the plugins are specified. Currently, the order of the same type of plugin (e.g. `binaryMavenPlugin`) is as the user specifies them in the pom. However, if someone wants to inject code in the output of a `jvmMavenPlugin` from a `binaryMavenPlugin`, according to the code in `SourceCodeGenerator.discoverPlugins`, this would not be possible. So maybe a ordering attribute could be added.

**Comment by ascopes** [comment]
Think that is reasonable to be honest. I'll raise an issue for it. Thanks.

**Comment by virgilsky** [comment]
I think the particular situation described above could also be managed with different executions and maven build stages though.
