### ISSUE TITLE
Resolving binary path plugins fails on Windows

### ISSUE THREAD

**Issue by virgilsky** [ascopes/protobuf-maven-plugin#271]
Resolving `binaryPathPlugins` fails on Windows, because the environment variables are case **insensitive** on this platform, i.e. both "Path" and "PATH" point to the same value.
However, when loading all the environment variables via `System.getenv()`, the generated map has case **sensitive** keys, which for Windows 10 for example would mean "Path" instead of "PATH". Luckily, the method `System.getenv("PATH")` takes care of such situations.
For that reason, I would propose to modify the constructor of `HostSystem` to pass an explicit `Map` of the required environment variables.

**Comment by ascopes** [comment]
Ah interesting! Good spot.

I wonder if we could alternatively change the overloaded constructor to take in `Function<String, String>` and pass in System::getenv directly which would handle case sensitivity based on the platform.

What do you think?

**Comment by virgilsky** [comment]
I agree with your suggestion. Avoiding passing in hardcoded keys is a more elegant solution. Thank you!

**Comment by ascopes** [comment]
@virgilsky I have just attempted to release it but Sonatype Nexus has been spuriously 401 and 500ing me all evening and is now just not loading at all on my side; going to wait until the morning and give it another go. Hope that is all okay.

**Comment by virgilsky** [comment]
@ascopes That is perfectly fine for me! Thank you!

**Comment by ascopes** [comment]
2.2.2 is on Maven Central. Thanks!
