### ISSUE TITLE
`src/main/protobuf` appears in the argline for `--proto_path` twice

### ISSUE THREAD

**Issue by ascopes** [ascopes/protobuf-maven-plugin#334]
It appears that running a simple project results in the `src/main/protobuf` arg being added to the `--proto_path` twice in the generated argument commandline.

The cause of this should be identified and fixed.

**Comment by optimusprike** [comment]
Hi! 👋 

I'm interested in contributing to open source projects and this issue came up as a good first issue. I tried to push my branch to make a PR, but I received a 403 error.

is it possible to get access so that I can push my branch and make a PR?

**Comment by ascopes** [comment]
Hey! If you click the fork button, you can work on your own copy of the project. GitHub will then let you raise a PR against this project once you are ready!

**Comment by optimusprike** [comment]
done, thanks!
