### ISSUE TITLE
Feature Request: Use .proto files from maven dependencies

### ISSUE THREAD

**Issue by JHahnHRO** [ascopes/protobuf-maven-plugin#38]
I'd like to see the following new feature:

I'd like to specify a list of some (not all) of my project's dependencies (jars and zips) that contain proto-files which the plugin should unpack and either compile directly or use for imports in other compilations.
If unpacking dependencies is too much of a hassle, then I'd like to see at least a way to distinguish between proto-files that get compiled  directly and proto-files that get only included for imports in other proto-files.

Background: Consider dependencies like com.google.protobuf:protobuf-java or com.google.api.grpc:proto-google-common-protos that contain both proto files and pre-compiled classes for those protos. If I want to use google.type.Date in my own proto-file, then I need the proto-files from proto-google-common-protos available during compilation, but I do not want them compiled themselves, only my own proto files, because the dependency already has the precompiled classes and I never want to compile things twice (duplicate classes lead to class path hell)

On the other hand: In my company there is an internal dependency for commonly used .proto files which does *not* contain pre-compiled classes. Those files I want available both as import and as input sources for compilation.

**Comment by ascopes** [comment]
Hey, thanks for this.

The latter use case should be quite simple. I can pass JARs directly to `--proto_path` so I could add a block to the configuration of the plugin that lets you pass Maven dependencies in directly like you do in the dependencies block. That'd then allow you to not bundle that JAR at runtime if you didn't want to (I can make that optional with scoping I think).

For the former, if the include path flag works just like the proto_path one does, I think this will be simple enough as well, off the top of my head.

Will see how it goes and what I can throw together and let you know.

**Comment by ascopes** [comment]
Hey, thanks for raising this.

I've put up a PR at GH-42 that should hopefully address the first part for you by allowing you to specify both directories and JARs (via identifiers such as `mvn:com.google.protobuf:protobuf-java:3.25.0`). I came across a couple of caveats with this that I've also had to address. 

The first is that I needed a way of making stuff within JARs visible to protoc (like you mentioned); for now I've implemented a mechanism that unpacks those dependencies to a directory within `target` from a virtual JAR filesystem. This should also work with ZIP files and WAR files, although I haven't tested that.

The second is that, for your example, `proto-google-common-protos` also depends on`protobuf-java` internally, so I've had to implement a dependency resolution mechanism (via the shared dependency API in Maven) that allows me to recursively get all the JARs in the dependency tree for a given artifact.

I wrote a very simple integration test case that pulls these in and it appears to all compile.

Would you be able to test the branch out and see if it fits your use case for the first part of your request?

---

For the second part, I think I need to have a bit more of a think about this, as I would need to decide how I need to deal with dependencies recursively when only some of them need compiling (e.g. do we want to compile dependencies of the original JAR, and where do we stop doing that without also hitting stuff like protobuf-java?)

If the internal dependency in your company contains the proto sources, would that be a more suitable place to also store the compiled sources for that specific project? 

If not, I can add the ability to do what you need, I just need to try and think of the best way of representing it without it being confusing or lacking behaviour for certain cases.

**Comment by ascopes** [comment]
Going to merge to main but will hold off releasing until I hear back

**Comment by joh-ivu** [comment]
Sorry for the delay. I'll try and have a look this week.

**Comment by ascopes** [comment]
Just as a heads up, I'm rewriting most of this plugin at the moment, so the way this gets loaded will change. Planning to instead just scan dependencies from the project itself rather than having dedicated configuration to it as that feels more idiomatic. I'll let you know when I've finished as I am working on it slowly when I have free time here and there.

**Comment by ascopes** [comment]
Going to close this as done on the basis of the import mechanism being implemented and now released to Maven Central.

If you have any issues, or still feel the compilation of sources in JARs is necessary, please can you open a new issue?

Thanks :-)

**Comment by ascopes** [comment]
Just a heads up on this, if you still need the ability to compile from JARs or ZIPs, then there is the stuff in place now for me to be able to support this. If you still need it, can you raise a new issue and I will sort it out as soon as I can.
