### ISSUE TITLE
Problem with jvm plugin

### ISSUE THREAD

**Issue by morvael** [ascopes/protobuf-maven-plugin#431]
I tried to write and use my own plugin. But the build process failed with:
```
common.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-_X21147SuBNvl0GbuRV6D12RgwA-0 hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
```
I think the problem lies in the auto-generated script which runs my jvm plugin. As the plugin itself is just a class with main, so it can't have or not have any kind of "support" here.

**Comment by morvael** [comment]
NVM, found out about `.setSupportedFeatures(CodeGeneratorResponse.Feature.FEATURE_PROTO3_OPTIONAL_VALUE)`

**Comment by ascopes** [comment]
Glad you found the solution!
